#!/bin/bash
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

# see if plots was edited in the last commit
editedfiles=$(git diff-tree --no-commit-id --name-only -r HEAD)


project_name=uwnet
report_server=olympus
public_url=https://atmos.washington.edu/~nbren12/reports/$project_name
report_dir=/home/disk/eos4/nbren12/public_html/reports/$project_name

for notebook in $editedfiles
do
    ext=${notebook##*.}
    namenoext=${notebook%.*}
    if [ $ext == "ipynb" ]; then
        chmod 0444 $notebook
        jupyter nbconvert $notebook
        html=$namenoext.html

        output_dir=$(realpath --relative-to='.' $(dirname $notebook))

        # make readable but not writeable
        chmod 0444 $html
        ssh $report_server mkdir -p $report_dir/$output_dir
        scp -p $html $report_server:$report_dir/$output_dir

        name=$(realpath --relative-to=$output_dir $namenoext.html)
        url=$public_url/$output_dir/$name
        echo "File URL: $url"
    fi
done
