#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

# check for dirty working tree

if ! git diff-files --quiet ||
   ! test -z "$(git ls-files --exclude-standard --others)"
then
echo "Untracked or un-staged files detected. Please commit these or add them"
echo "to gitignore."
echo 

    echo "Untracked files"
    echo "---------------"
    git ls-files --exclude-standard --others


    exit 1
fi

# if ! pytest
# then
#     echo "pytest failed...commit anyway [y/n]"
#     read answer
#     case answer in
#         y) exit 0
#             ;;
#         *) exit 1 ;;
#     esac
# fi
