version: '2.3'
services:
  sam:
    build: ./
    environment:
      - LOCAL_FLAGS=/uwnet/setup/docker/local_flags.mk
      - REDIS_URL=redis
      - NGAQUA_PATH=/uwnet/data/processed/training.nc
    volumes:
      - ./uwnet:/opt/uwnet
      - ./:/uwnet
      - ./ext/sam:/opt/sam
  jupyter:
    build: 
      context: .
      dockerfile: Dockerfile.jupyter
    runtime: nvidia
    volumes:
      - ./:/opt/uwnet
      - /home/paperspace/.jupyter:/root/.jupyter
      - /storage:/storage
    ports:
      - "8888:8888"
  bash:
    image: nbren12/uwnet:latest
    runtime: nvidia
    volumes:
      - ./:/opt/uwnet
      - /home/paperspace/.jupyter:/root/.jupyter
      - /storage:/storage
